os:
  - linux
language: python
python:
  - "3.6"
before_install:
  - pip install codecov pytest-cov
  - pip install -r requirements.txt
script:
  - py.test --cov=hydra_agent tests/
after_success:
    codecov
